name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v7
      with:
        fetch-depth: 1
        filter: blob:none
        sparse-checkout: |
          notebooks
          scripts
          sketches
          src
          tests
          pyproject.toml
          Makefile
          .clang-format
          .github
        sparse-checkout-cone-mode: true
    - name: Set up Python
      uses: actions/setup-python@v6.3.0
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        make setup-dev

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make test_ci